version: '3'
services:
  algoritmosja-app:
    build: .
    ports:
      - "3000:80"  # Mapea el puerto 80 del contenedor al puerto 3000 de tu máquina
    networks:
      -  algoritmosja-network
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf  # Asegúrate de que nginx.conf está en la raíz del proyecto

networks:
  algoritmosja-network:
    external: true