version: '3'
services:
  algoritmosja-app:
    build: .
    ports:
      - "3000:80"  
    networks:
      -  algoritmosja-network
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf  

networks:
  algoritmosja-network:
    external: true
